# *******  DEFAULT  *******
# spring.jpa.hibernate.ddl-auto: create-drop
# spring.jpa.hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
# spring.jpa.database: H2
# spring.jpa.show-sql: true
---
spring:
  mvc:
    favicon:
      enabled: false

  jpa:
    show-sql: false

  application:
    name: test-status

  profiles:
    default: ${ENV:dev}

  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

configuration:
    projectName: test-status-default

    default:
      browser: firefox
      platform: linux

    udp:
      port: 6500
      host: localhost

    testdata: false
    initialdata: true

    schedule:
      synchwithjenkins:
        rate: 60000
        
      statcalc:
        rate: 1000
        
      cleanup:
        rate: 1000
        delay: 5000
        cron: "1 0 * * * *"

      testresult:
        rate: 1000
        delay: 5000

      handleresults:
        rate: 500
        delay: 5000

      hourly:
        cron: "1 0 * * * *"
        delay: 5000

      daily:
        cron: "1 0 0 * * *"
        delay: 5000

    storagedays: 5
    storedresults: 30

    log:
      receivedresult: false
      sendtestdata: false
      deletions: false
      
    jenkins:
      apisuffix: /api/json
      testreportsuffix: testReport
      lastreportsuffix: lastBuild
info:
  app:
    name: ${spring.application.name}
    version: ${VERSION:unknown}

server:
  port: ${port:8090}

# ***********************
# ***********************
# *******  STAGE  *******
# ***********************
# ***********************
---
spring:
  profiles: stage

  jpa:
    show-sql: false

  datasuorce:
    url: postgres://iyfgdecpmudmfo:yH4dXI2jVTgFQ8Js5n6djW4bgR@ec2-107-21-114-132.compute-1.amazonaws.com:5432/dtq22ng04anf3
    username: iyfgdecpmudmfo
    password: yH4dXI2jVTgFQ8Js5n6djW4bgR

configuration:
  projectName: test-status-stage
  testdata: false
  initialdata: false

  log:
    receivedresult: false
    sendtestdata: false

# ***********************
# ***********************
# *******  PROD  ********
# ***********************
# ***********************
---
spring:
  profiles: prod

  jpa:
    show-sql: false

configuration:
  projectName: test-status-prod
  testdata: false
  initialdata: false

  log:
    receivedresult: false
    sendtestdata: false

server:
  port: ${port:8090}
