# *******  DEFAULT  *******
# spring.jpa.hibernate.ddl-auto: create-drop
# spring.jpa.hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
# spring.jpa.database: H2
# spring.jpa.show-sql: true

spring:
  mvc:
    favicon:
      enabled: false

  jpa:
    hibernate:
        show-sql: true

    show-sql: true

  application:
    name: test-status

  profiles:
    default: ${ENV:dev}

  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

info:
  app:
    name: ${spring.application.name}
    version: ${VERSION:unknown}

server:
  port: ${port:8090}
  
configuration:
    projectName: test-status
    default:
      browser: firefox
      platform: linux

org:
  hibernate:
    show-sql: true

hibernate:
  show-sql: true
# *******  DEV  *******

---
spring:
  profiles: dev

hibernate:
  connection:
    username: root
    password: root
    driver_class: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306:test


configuration:
  projectName: test-status-dev


# *******  STAGE  *******

---
spring:
  profiles: stage

  datasuorce:
    url: postgres://iyfgdecpmudmfo:yH4dXI2jVTgFQ8Js5n6djW4bgR@ec2-107-21-114-132.compute-1.amazonaws.com:5432/dtq22ng04anf3
    username: iyfgdecpmudmfo
    password: yH4dXI2jVTgFQ8Js5n6djW4bgR

configuration:
  projectName: test-status-stage

# *******  PROD  *******

---
spring:
  profiles: prod

configuration:
  projectName: test-status-prod

server:
  port: ${port:80}