# *******  DEFAULT  *******
# spring.jpa.hibernate.ddl-auto: create-drop
# spring.jpa.hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
# spring.jpa.database: H2
# spring.jpa.show-sql: true

configuration:
    projectName: test-status

    default:
      browser: firefox
      platform: linux

    udp:
      port: 6500
      host: localhost

    testdata: true

    schedule:
      cleanup:
        rate: 1000
        delay: 5000

      testresult:
        rate: 1000
        delay: 5000

      handleresults:
        rate: 500
        delay: 5000

      hourly:
        cron: "1 0 * * * *"
        delay: 5000

      dayly:
        cron: "1 0 0 * * *"
        delay: 5000

    log:
      receivedresult: true
      senttestdatas: false



spring:
  mvc:
    favicon:
      enabled: false

  jpa:
    show-sql: false

  application:
    name: test-status

  profiles:
    default: ${ENV:dev}

  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

info:
  app:
    name: ${spring.application.name}
    version: ${VERSION:unknown}

server:
  port: ${port:8090}

# ***********************
# ***********************
# *******  DEV  *********
# ***********************
# ***********************
---
spring:
  profiles: dev

configuration:
  projectName: test-status-dev
  testdata: true

hibernate:
  connection:
    username: root
    password: root
    driver_class: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306:test

# ***********************
# ***********************
# *******  STAGE  *******
# ***********************
# ***********************
---
spring:
  profiles: stage

  jpa:
    show-sql: false

  datasuorce:
    url: postgres://iyfgdecpmudmfo:yH4dXI2jVTgFQ8Js5n6djW4bgR@ec2-107-21-114-132.compute-1.amazonaws.com:5432/dtq22ng04anf3
    username: iyfgdecpmudmfo
    password: yH4dXI2jVTgFQ8Js5n6djW4bgR

configuration:
  projectName: test-status-stage
  testdata: false

# ***********************
# ***********************
# *******  PROD  ********
# ***********************
# ***********************
---
spring:
  profiles: false

  jpa:
    show-sql: false

configuration:
  projectName: test-status-prod
  testdata: false

server:
  port: ${port:80}
